import {
    createAlignPlugin,
    createAutoformatPlugin,
    createBlockquotePlugin,
    createBoldPlugin,
    createCodeBlockPlugin,
    createCodePlugin,
    createComboboxPlugin,
    createDeserializeCsvPlugin,
    createDeserializeDocxPlugin,
    createDeserializeHtmlPlugin,
    createDeserializeMdPlugin,
    createExitBreakPlugin,
    createFontBackgroundColorPlugin,
    createFontColorPlugin,
    createFontFamilyPlugin,
    createFontSizePlugin,
    createFontWeightPlugin,
    createHeadingPlugin,
    createHighlightPlugin,
    createHorizontalRulePlugin,
    createImagePlugin,
    createIndentPlugin,
    createItalicPlugin,
    createJuicePlugin,
    createKbdPlugin,
    createLineHeightPlugin,
    createLinkPlugin,
    createListPlugin,
    createMediaEmbedPlugin,
    createNodeIdPlugin,
    createNormalizeTypesPlugin,
    createParagraphPlugin,
    createPlateUI,
    createPluginFactory,
    createPlugins,
    createResetNodePlugin,
    createSelectOnBackspacePlugin,
    createSoftBreakPlugin,
    createStrikethroughPlugin,
    createSubscriptPlugin,
    createSuperscriptPlugin,
    createTablePlugin,
    createTodoListPlugin,
    createTrailingBlockPlugin,
    createUnderlinePlugin, parseHtmlDocument, deserializeHtml
} from "@udecode/plate";
import {withStyledPlaceHolders} from "./Toolbars";
import {config} from "./config";

let components = createPlateUI();
components = withStyledPlaceHolders(components);

export const plugins = createPlugins([
    createParagraphPlugin(),
    createBlockquotePlugin(),
    createTodoListPlugin(),
    createHeadingPlugin(),
    createImagePlugin(),
    createHorizontalRulePlugin(),
    createLineHeightPlugin(config.lineHeight),
    createLinkPlugin(),
    createListPlugin(),
    createTablePlugin(),
    createMediaEmbedPlugin(),
    createCodeBlockPlugin(),
    createAlignPlugin(config.align),
    createBoldPlugin(),
    createCodePlugin(),
    createItalicPlugin(),
    createHighlightPlugin(),
    createUnderlinePlugin(),
    createStrikethroughPlugin(),
    createSubscriptPlugin(),
    createSuperscriptPlugin(),
    createFontBackgroundColorPlugin(),
    createFontFamilyPlugin(),
    createFontColorPlugin(),
    createFontSizePlugin(),
    createFontWeightPlugin(),
    createKbdPlugin(),
    createNodeIdPlugin(),
    createIndentPlugin(config.indent),
    createAutoformatPlugin(config.autoformat),
    createResetNodePlugin(config.resetBlockType),
    createSoftBreakPlugin(config.softBreak),
    createExitBreakPlugin(config.exitBreak),
    createNormalizeTypesPlugin(config.forceLayout),
    createTrailingBlockPlugin(config.trailingBlock),
    createSelectOnBackspacePlugin(config.selectOnBackspace),
    createComboboxPlugin(),
    createJuicePlugin(),
    createDeserializeHtmlPlugin()
], {
    components,
});